{"event": "runner_on_failed", "uuid": "65d3cca1-4d75-4a4a-9e5e-d737b7123548", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": false, \"msg\": \"network network12 not found\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "counter": 19, "pid": 23190, "created": "2019-11-10T23:36:20.338194", "end_line": 30, "runner_ident": "48b1522f-4085-48d0-a158-35ce60033773", "start_line": 28, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "65d3cca1-4d75-4a4a-9e5e-d737b7123548", "remote_addr": "127.0.0.1", "res": {"deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "_ansible_no_log": false, "changed": false, "msg": "network network12 not found", "invocation": {"module_args": {"xml": null, "name": "network12", "uri": "qemu:///system", "state": null, "command": "create", "autostart": null}}, "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}}, "play_uuid": "52540074-89e3-ee60-efb9-000000000008", "task_uuid": "52540074-89e3-ee60-efb9-00000000000c", "task": "Create Virtual Network if not created", "playbook_uuid": "26ea7630-f97f-4082-aefb-445cf932d11a", "playbook": "routerConnectionCreation.yaml", "task_action": "virt_net", "host": "127.0.0.1", "ignore_errors": true, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:26"}, "parent_uuid": "52540074-89e3-ee60-efb9-00000000000c"}