{"event": "runner_on_failed", "uuid": "80b3dbf8-eda3-43bc-8b09-c9ada4d3db46", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": true, \"cmd\": [\"virsh\", \"attach-interface\", \"\u2013domain\", \"routerConnectionParams.sourceRouter\", \"\u2013type\", \"network\", \"\u2013source\", \"routers.networkName\", \"\u2013model\", \"virtio\", \"\u2013mac\", \"{stderr_lines:\", \"[],\", \"stdout:\", \"u31:c8:81:d9:2b:1b\\\\n,\", \"changed:\", \"True,\", \"failed:\", \"False,\", \"stderr:\", \"u,\", \"rc:\", \"0,\", \"stdout_lines:\", \"[u31:c8:81:d9:2b:1b]}\", \"\u2013config\", \"\u2013live\"], \"delta\": \"0:00:00.034496\", \"end\": \"2019-11-10 22:16:37.524169\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2019-11-10 22:16:37.489673\", \"stderr\": \"error: unexpected data '{stderr_lines:'\", \"stderr_lines\": [\"error: unexpected data '{stderr_lines:'\"], \"stdout\": \"\", \"stdout_lines\": []}\u001b[0m", "counter": 27, "pid": 20127, "created": "2019-11-10T22:16:37.586772", "end_line": 39, "runner_ident": "3c18c81e-3e3c-477d-9028-9a9c22b4ee20", "start_line": 38, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "80b3dbf8-eda3-43bc-8b09-c9ada4d3db46", "remote_addr": "127.0.0.1", "res": {"stderr_lines": ["error: unexpected data '{stderr_lines:'"], "deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "cmd": ["virsh", "attach-interface", "\u2013domain", "routerConnectionParams.sourceRouter", "\u2013type", "network", "\u2013source", "routers.networkName", "\u2013model", "virtio", "\u2013mac", "{stderr_lines:", "[],", "stdout:", "u31:c8:81:d9:2b:1b\\n,", "changed:", "True,", "failed:", "False,", "stderr:", "u,", "rc:", "0,", "stdout_lines:", "[u31:c8:81:d9:2b:1b]}", "\u2013config", "\u2013live"], "end": "2019-11-10 22:16:37.524169", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 1, "start": "2019-11-10 22:16:37.489673", "stderr": "error: unexpected data '{stderr_lines:'", "delta": "0:00:00.034496", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "virsh attach-interface \u2013domain routerConnectionParams.sourceRouter \u2013type network \u2013source routers.networkName \u2013model virtio \u2013mac {'stderr_lines': [], 'stdout': u'31:c8:81:d9:2b:1b\\n', 'changed': True, 'failed': False, 'stderr': u'', 'rc': 0, 'stdout_lines': [u'31:c8:81:d9:2b:1b']} \u2013config \u2013live", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": [], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "msg": "non-zero return code"}, "play_uuid": "52540074-89e3-359b-9642-000000000008", "task_uuid": "52540074-89e3-359b-9642-00000000000f", "task": "Attach network to R1", "playbook_uuid": "ffbef508-d0f9-4906-a647-60158227af95", "playbook": "routerConnectionCreation.yaml", "task_action": "command", "host": "127.0.0.1", "ignore_errors": null, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:43"}, "parent_uuid": "52540074-89e3-359b-9642-00000000000f"}