{"event": "runner_on_failed", "uuid": "7c7518b2-e43b-47a4-a913-88a9a5df46f5", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": false, \"msg\": \"network network12 not found\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "counter": 19, "pid": 22545, "created": "2019-11-10T23:33:12.783375", "end_line": 30, "runner_ident": "fda45be8-0957-4a82-830e-e6b351dcb0ff", "start_line": 28, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "7c7518b2-e43b-47a4-a913-88a9a5df46f5", "remote_addr": "127.0.0.1", "res": {"deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "_ansible_no_log": false, "changed": false, "msg": "network network12 not found", "invocation": {"module_args": {"xml": null, "name": "network12", "uri": "qemu:///system", "state": null, "command": "create", "autostart": null}}, "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}}, "play_uuid": "52540074-89e3-2fd3-e7c0-000000000008", "task_uuid": "52540074-89e3-2fd3-e7c0-00000000000c", "task": "Create Virtual Network if not created", "playbook_uuid": "71cf509d-773d-4a9a-9ef7-b8e520637dc6", "playbook": "routerConnectionCreation.yaml", "task_action": "virt_net", "host": "127.0.0.1", "ignore_errors": true, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:26"}, "parent_uuid": "52540074-89e3-2fd3-e7c0-00000000000c"}