{"event": "runner_on_failed", "uuid": "e55e5d11-f35c-41a5-809a-edc30c4a4519", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": true, \"cmd\": [\"virsh\", \"attach-interface\", \"\u2013domain\", \"routerConnectionParams.sourceRouter\", \"\u2013type\", \"network\", \"\u2013source\", \"routers.networkName\", \"\u2013model\", \"virtio\", \"\u2013mac\", \"{stderr_lines:\", \"[],\", \"stdout:\", \"u46:ca:21:d3:c7:59\\\\n,\", \"changed:\", \"True,\", \"failed:\", \"False,\", \"stderr:\", \"u,\", \"rc:\", \"0,\", \"stdout_lines:\", \"[u46:ca:21:d3:c7:59]}\", \"\u2013config\", \"\u2013live\"], \"delta\": \"0:00:00.031344\", \"end\": \"2019-11-10 23:33:14.090217\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2019-11-10 23:33:14.058873\", \"stderr\": \"error: unexpected data '{stderr_lines:'\", \"stderr_lines\": [\"error: unexpected data '{stderr_lines:'\"], \"stdout\": \"\", \"stdout_lines\": []}\u001b[0m", "counter": 28, "pid": 22545, "created": "2019-11-10T23:33:14.138588", "end_line": 39, "runner_ident": "fda45be8-0957-4a82-830e-e6b351dcb0ff", "start_line": 38, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "e55e5d11-f35c-41a5-809a-edc30c4a4519", "remote_addr": "127.0.0.1", "res": {"stderr_lines": ["error: unexpected data '{stderr_lines:'"], "deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "cmd": ["virsh", "attach-interface", "\u2013domain", "routerConnectionParams.sourceRouter", "\u2013type", "network", "\u2013source", "routers.networkName", "\u2013model", "virtio", "\u2013mac", "{stderr_lines:", "[],", "stdout:", "u46:ca:21:d3:c7:59\\n,", "changed:", "True,", "failed:", "False,", "stderr:", "u,", "rc:", "0,", "stdout_lines:", "[u46:ca:21:d3:c7:59]}", "\u2013config", "\u2013live"], "end": "2019-11-10 23:33:14.090217", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 1, "start": "2019-11-10 23:33:14.058873", "stderr": "error: unexpected data '{stderr_lines:'", "delta": "0:00:00.031344", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "virsh attach-interface \u2013domain routerConnectionParams.sourceRouter \u2013type network \u2013source routers.networkName \u2013model virtio \u2013mac {'stderr_lines': [], 'stdout': u'46:ca:21:d3:c7:59\\n', 'changed': True, 'failed': False, 'stderr': u'', 'rc': 0, 'stdout_lines': [u'46:ca:21:d3:c7:59']} \u2013config \u2013live", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": [], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "msg": "non-zero return code"}, "play_uuid": "52540074-89e3-2fd3-e7c0-000000000008", "task_uuid": "52540074-89e3-2fd3-e7c0-00000000000f", "task": "Attach network to R1", "playbook_uuid": "71cf509d-773d-4a9a-9ef7-b8e520637dc6", "playbook": "routerConnectionCreation.yaml", "task_action": "command", "host": "127.0.0.1", "ignore_errors": null, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:42"}, "parent_uuid": "52540074-89e3-2fd3-e7c0-00000000000f"}