{"event": "runner_on_failed", "uuid": "62a5be73-2754-4fb2-a8f2-8648ad44ccf0", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": true, \"cmd\": [\"virsh\", \"attach-interface\", \"\u2013domain\", \"item.sourceRouter\", \"\u2013type\", \"network\", \"\u2013source\", \"item.networkName\", \"\u2013model\", \"virtio\", \"\u2013mac\", \"{stderr_lines:\", \"[],\", \"stdout:\", \"u43:de:e6:ba:03:12\\\\n,\", \"changed:\", \"True,\", \"failed:\", \"False,\", \"stderr:\", \"u,\", \"rc:\", \"0,\", \"stdout_lines:\", \"[u43:de:e6:ba:03:12]}\", \"\u2013config\", \"\u2013live\"], \"delta\": \"0:00:00.030783\", \"end\": \"2019-11-10 21:58:20.270074\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2019-11-10 21:58:20.239291\", \"stderr\": \"error: unexpected data '{stderr_lines:'\", \"stderr_lines\": [\"error: unexpected data '{stderr_lines:'\"], \"stdout\": \"\", \"stdout_lines\": []}\u001b[0m", "counter": 28, "pid": 19649, "created": "2019-11-10T21:58:20.323300", "end_line": 42, "runner_ident": "45b3d937-d063-4718-94ff-47c6258f1065", "start_line": 41, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "62a5be73-2754-4fb2-a8f2-8648ad44ccf0", "remote_addr": "127.0.0.1", "res": {"stderr_lines": ["error: unexpected data '{stderr_lines:'"], "deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "cmd": ["virsh", "attach-interface", "\u2013domain", "item.sourceRouter", "\u2013type", "network", "\u2013source", "item.networkName", "\u2013model", "virtio", "\u2013mac", "{stderr_lines:", "[],", "stdout:", "u43:de:e6:ba:03:12\\n,", "changed:", "True,", "failed:", "False,", "stderr:", "u,", "rc:", "0,", "stdout_lines:", "[u43:de:e6:ba:03:12]}", "\u2013config", "\u2013live"], "end": "2019-11-10 21:58:20.270074", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 1, "start": "2019-11-10 21:58:20.239291", "stderr": "error: unexpected data '{stderr_lines:'", "delta": "0:00:00.030783", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "virsh attach-interface \u2013domain item.sourceRouter \u2013type network \u2013source item.networkName \u2013model virtio \u2013mac {'stderr_lines': [], 'stdout': u'43:de:e6:ba:03:12\\n', 'changed': True, 'failed': False, 'stderr': u'', 'rc': 0, 'stdout_lines': [u'43:de:e6:ba:03:12']} \u2013config \u2013live", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": [], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "msg": "non-zero return code"}, "play_uuid": "52540074-89e3-3347-522e-000000000008", "task_uuid": "52540074-89e3-3347-522e-00000000000f", "task": "Attach network to R1", "playbook_uuid": "2f8d9412-2d27-45cf-8167-a8b2b0066a65", "playbook": "routerConnectionCreation.yaml", "task_action": "command", "host": "127.0.0.1", "ignore_errors": null, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:41"}, "parent_uuid": "52540074-89e3-3347-522e-00000000000f"}