{"event": "runner_on_failed", "uuid": "764c2371-21de-4ed3-b3b7-0a131f9bf9a1", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": false, \"msg\": \"network network12 not found\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "counter": 19, "pid": 19823, "created": "2019-11-10T22:09:17.621650", "end_line": 33, "runner_ident": "285e8152-e428-47ea-ad6e-6452344ec51a", "start_line": 31, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "764c2371-21de-4ed3-b3b7-0a131f9bf9a1", "remote_addr": "127.0.0.1", "res": {"deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "_ansible_no_log": false, "changed": false, "msg": "network network12 not found", "invocation": {"module_args": {"xml": null, "name": "network12", "uri": "qemu:///system", "state": null, "command": "create", "autostart": null}}, "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}}, "play_uuid": "52540074-89e3-f2e9-6cb5-000000000008", "task_uuid": "52540074-89e3-f2e9-6cb5-00000000000c", "task": "Create Virtual Network if not created", "playbook_uuid": "7e01fcf4-9473-4f9b-9d4f-71f468a900a4", "playbook": "routerConnectionCreation.yaml", "task_action": "virt_net", "host": "127.0.0.1", "ignore_errors": true, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:25"}, "parent_uuid": "52540074-89e3-f2e9-6cb5-00000000000c"}