{"event": "runner_on_failed", "uuid": "ead41643-b379-4efd-a695-2ac6701c6668", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": true, \"cmd\": [\"virsh\", \"attach-interface\", \"\u2013domain\", \"routers.sourceRouter\", \"\u2013type\", \"network\", \"\u2013source\", \"routers.networkName\", \"\u2013model\", \"virtio\", \"\u2013mac\", \"{stderr_lines:\", \"[],\", \"stdout:\", \"u79:82:68:20:8b:d2\\\\n,\", \"changed:\", \"True,\", \"failed:\", \"False,\", \"stderr:\", \"u,\", \"rc:\", \"0,\", \"stdout_lines:\", \"[u79:82:68:20:8b:d2]}\", \"\u2013config\", \"\u2013live\"], \"delta\": \"0:00:00.032887\", \"end\": \"2019-11-10 22:09:18.968611\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2019-11-10 22:09:18.935724\", \"stderr\": \"error: unexpected data '{stderr_lines:'\", \"stderr_lines\": [\"error: unexpected data '{stderr_lines:'\"], \"stdout\": \"\", \"stdout_lines\": []}\u001b[0m", "counter": 28, "pid": 19823, "created": "2019-11-10T22:09:19.015811", "end_line": 42, "runner_ident": "285e8152-e428-47ea-ad6e-6452344ec51a", "start_line": 41, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "ead41643-b379-4efd-a695-2ac6701c6668", "remote_addr": "127.0.0.1", "res": {"stderr_lines": ["error: unexpected data '{stderr_lines:'"], "deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "cmd": ["virsh", "attach-interface", "\u2013domain", "routers.sourceRouter", "\u2013type", "network", "\u2013source", "routers.networkName", "\u2013model", "virtio", "\u2013mac", "{stderr_lines:", "[],", "stdout:", "u79:82:68:20:8b:d2\\n,", "changed:", "True,", "failed:", "False,", "stderr:", "u,", "rc:", "0,", "stdout_lines:", "[u79:82:68:20:8b:d2]}", "\u2013config", "\u2013live"], "end": "2019-11-10 22:09:18.968611", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 1, "start": "2019-11-10 22:09:18.935724", "stderr": "error: unexpected data '{stderr_lines:'", "delta": "0:00:00.032887", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "virsh attach-interface \u2013domain routers.sourceRouter \u2013type network \u2013source routers.networkName \u2013model virtio \u2013mac {'stderr_lines': [], 'stdout': u'79:82:68:20:8b:d2\\n', 'changed': True, 'failed': False, 'stderr': u'', 'rc': 0, 'stdout_lines': [u'79:82:68:20:8b:d2']} \u2013config \u2013live", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": [], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "msg": "non-zero return code"}, "play_uuid": "52540074-89e3-f2e9-6cb5-000000000008", "task_uuid": "52540074-89e3-f2e9-6cb5-00000000000f", "task": "Attach network to R1", "playbook_uuid": "7e01fcf4-9473-4f9b-9d4f-71f468a900a4", "playbook": "routerConnectionCreation.yaml", "task_action": "command", "host": "127.0.0.1", "ignore_errors": null, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:41"}, "parent_uuid": "52540074-89e3-f2e9-6cb5-00000000000f"}